#!/bin/ksh

daemon="/usr/local/bin/diode_send"
daemon_flags="--directory /var/www/diode --device /dev/cuaU0"

. /etc/rc.d/rc.subr

rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} 2>&1"
}

rc_cmd $1
