#!/bin/ksh

daemon="/usr/local/bin/diode_send"
daemon_flags="--directory /home/diode/send"
daemon_user="diode"

. /etc/rc.d/rc.subr

pexp="python3 \/usr\/local\/bin\/diode_send(.*)"

rc_start() {
        logger "Starting diode sender with flags ${daemon_flags}"
        rc_exec "${daemon} ${daemon_flags} &"
}

rc_cmd $1
