#!/bin/ksh

daemon="/usr/local/bin/diode_receive"
daemon_flags="--directory /var/www/diode --device /dev/cuaU0 --arduino /dev/cuaU1"

. /etc/rc.d/rc.subr

rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} 2>&1 | logger -t diode-receive &"
}

rc_cmd $1
