#!/bin/ksh

daemon="/usr/local/bin/diode_receive"
daemon_flags="--directory /home/diode/receive --arduino /dev/cuaU0"
daemon_user="diode"

. /etc/rc.d/rc.subr

pexp="python3 \/usr\/local\/bin\/diode_receive(.*)"

rc_start() {
        logger "Starting diode receiver with flags ${daemon_flags}"
        rc_exec "${daemon} ${daemon_flags} &"
}

rc_cmd $1
